apiVersion: apps/v1
kind: Deployment
metadata:
  name: tickets-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tickets
  template:
    metadata:
      labels:
        app: tickets
    spec:
      containers:
        - name: tickets
          image: nero20052023/ticketing-tickets
          env:
            - name: JWT_KEY
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: JWT_KEY
            - name: NODE_ENV
              value: development
            - name: TICKETS_DATABASE_URL
              value: "mongodb+srv://Nero2005:mernstack@cluster0.2uruf.mongodb.net/ticketing-tickets?retryWrites=true&w=majority"
            - name: NATS_CLUSTER_ID
              value: ticketing
            - name: NATS_URL
              value: http://nats-clusterip-srv:4222
            - name: NATS_CLIENT_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
          command: ["yarn", "start"]
---
apiVersion: v1
kind: Service
metadata:
  name: tickets-clusterip-srv
spec:
  selector:
    app: tickets
  ports:
    - name: tickets
      protocol: TCP
      port: 3000
      targetPort: 3000
