apiVersion: apps/v1
kind: Deployment
metadata:
  name: expiration-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: expiration
  template:
    metadata:
      labels:
        app: expiration
    spec:
      containers:
        - name: expiration
          image: nero20052023/ticketing-expiration
          env:
            - name: NODE_ENV
              value: development
            - name: REDIS_HOST
              value: expiration-redis-srv
            - name: NATS_CLUSTER_ID
              value: ticketing
            - name: NATS_URL
              value: http://nats-clusterip-srv:4222
            - name: NATS_CLIENT_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
          command: ["yarn", "start"]
